spring:
  application:
    name: turbine
server:
  port: 9402

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/

management:
  server:
    #actuator端口
    port: 9402
  endpoints:
    web:
      #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
#      base-path: /actuator
      exposure:
        #开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always

turbine:
  app-config: FEIGN-CLIENT,GATEWAY
  cluster-name-expression: new String("default")
  combine-host-port: true
