spring:
  application:
    name: feign-client

server:
  port: 9301

eureka:
  client:
    service-url:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always

logging:
  level:
    com.xieyu.feignclient.feign: debug

